name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
jobs:
  full-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update submodules
        run: git submodule update --recursive
      - name: Run full test
        run: ./full-test.sh
